//
//  Command.h
//  BoXiu
//
//  Created by Andy on 14-4-11.
//  Copyright (c) 2014年 rexiu. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef short COMMAND_ID;

static COMMAND_ID CM_AUTH = 01;
static COMMAND_ID CM_ENTERROOM = 50;
static COMMAND_ID CM_EXITROOM = 52;
static COMMAND_ID CM_SEND_MESSAGE = 101;

static COMMAND_ID CM_AUTH_RESULT = 11;
static COMMAND_ID CM_HEART = 02;
static COMMAND_ID CM_ENTERROOM_RESULT = 51;
static COMMAND_ID CM_RECEIVE_MESSAGE = 102;     //收到房间消息
static COMMAND_ID CM_GLOBAL_MESSAGE = 300;

static COMMAND_ID CM_GIVE_GIFT = 201;
static COMMAND_ID CM_RECEIVE_GIFT = 202;

static COMMAND_ID CM_Hert = 402;//心跳

static COMMAND_ID CM_ROB_SOFA = 211;
static COMMAND_ID CM_RECEIVE_SOFA = 212;

static COMMAND_ID CM_RECEIVE_ERRO = 400;
static COMMAND_ID CM_SENDNOTICE_MESSAGE = 401;//首次触发点赞效果通知

static COMMAND_ID CM_GET_APPROVE = 221;
static COMMAND_ID CM_GET_APPROVE_RESULT = 222;

static COMMAND_ID CM_SEND_APPROVE = 223;
static COMMAND_ID CM_SEND_APPROVE_RESULT = 2241;     //送赞

//static COMMAND_ID CM_SEND_APPROVE_RESULT = 224;     //旧的送赞  

static COMMAND_ID CM_SEND_BARAGEMESSAGE = 225;
static COMMAND_ID CM_RECEIVE_BARAGEMESSAGE = 226;

static COMMAND_ID CM_RECEIVE_ENTNERROOM_MESSAGE = 231;//用户进入房间的消息

static COMMAND_ID CM_RECEIVE_SHOWTIMECHANGE_MESSAGE = 240;//切换到showtime
static COMMAND_ID CM_RECEIVE_SHOWTIMEBEGIN_MESSAGE = 241;//showTime开始
static COMMAND_ID CM_RECEIVE_SHOWTIMEEND_MESSAGE = 242;//showTIme结束

static COMMAND_ID CM_RECEIVE_MUSICCHANGE_MESSAGE = 250;//切换到点歌
static COMMAND_ID CM_SEND_SHOWTIME_APPROVE = 243;//showtime点赞
static COMMAND_ID CM_SEND_SHOWTIME_APPROVE_RESULT = 245;//点赞收费赞返回结果
static COMMAND_ID CM_OUT_ROOM = 232;//退出房间


static COMMAND_ID CM_RECEIVE_SHOWTIME_DATA_MESSAGE = 244;//showtime进行时
