#ifndef ALLFILTERS_H
#define ALLFILTERS_H

typedef enum MSFilterId{
	MS_FILTER_NOT_SET_ID,
	MS_FILTER_PLUGIN_ID,	/* no type checking will be performed on plugins */ //MS_SPEEX_EC_ID,
	MS_FILTER_BASE_ID,
	MS_AUDIO_DEC_RECV_ID,
	MS_AUDIO_ENC_SEND_ID,
    MS_SPEEX_EC_ID,
	MS_AUDIO_RECORDER_ID,
	MS_AUDIOCALL_PLAYER_ID,
    MS_AUDIOROOM_PLAYER_ID,
    MS_AUDIO_DEC_RECV_SINGLE_ID,
    MS_VIDEO_RECV_SINGLE_ID,
    MS_ANDROID_DISPLAY_ID,
    MS_VIDEO_RECORDER_ID,
    MS_VIDEO_PLAYER_ID,
    MS_AUDIO_PLAYER_ID,
    MS_AUDIOUNIT_PLAYER_ID,
    MS_AUDIOQUEUE_PLAYER_ID
} MSFilterId;

#endif

